### ISSUE TITLE
Location based messaging

### ISSUE THREAD

**Issue by orsondmc** [team-catgirl/collar#57]
Need to make sure this scenario doesn't occur

```
bad player: messaging.sendWithinLocation(location, bounds, new TextMessage('hi there');
good player: messaging.sendPrivate(location, bounds,new TextMessage('hello?');
bad player: messaging.sendPrivate(location, bounds,new TextMessage('see u soon');
```

I recommend that all players send who's in their render distance. We store this state and index it.

when `messaging.sendNearby(message)` is called, the server determines (using a cartesian product) if the sender has any players in common with other players. If so, the message is delivered to those in common.

Mongo supports this using [setIntersection](https://docs.mongodb.com/manual/reference/operator/aggregation/setIntersection/)

`{ $setIntersection: [ [ "a", "b", "a" ], [ "b", "a" ] ] } -> [ "b", "a" ]`  where `b` and `a` are the players we can forward the message to. 

Set must contain the owner of the set otherwise this won't work

**Comment by aGreenLizard** [comment]
To ensure no security holes while keeping this feature user friendly I suggest the use of expiring message tokens or something of the like.

The server, as you said, should only create a chat room between multiple parties if according to all participants they can each see each other. This can be done by a simple, mutual, "I have seen you" message. This token or flag would expire after a short time, say 30 seconds, to buffer the case of nearby players going in and out of render distance.

After a chat room is set up between all parties, a user should only be known of if they freely speak in the chat. This chat room should not tell users how many users are there nor if any users are even there or still there.

While entity sharing can achieve the same result, the server would need to be the one to make that determination which would involve being trusted to know everyone's entities locations and do comparisons with all parties data.

**Comment by orsondmc** [comment]
@aGreenLizard i love the idea of a temporary group based on nearby location! Very cool idea and we can build upon it for other things.

As soon as I have group encryption working we can pick this up!

**Comment by orsondmc** [comment]
DONE!!
